- name: Setup a new Raspberry pi
  hosts: all
  tasks:
    - name: Ensure en_US locale exists
      community.general.locale_gen:
        name: en_US.UTF-8
        state: present

    - name: Install raspotify
      import_role:
        name: raspotify
      vars:
        device_name: '"Schreibtisch"'
        bitrate: '"320"'

    - name: Install Homebridge
      import_role:
        name: homebridge
