- name: Setup a new Raspberry pi
  hosts: all
  pre_tasks:
    - name: Ensure en_US locale exists
      community.general.locale_gen:
        name: en_US.UTF-8
        state: present

  roles:
    - name: Install raspotify
      role: raspotify
      device_name: '"Schreibtisch"'
      bitrate: '"320"'

    - name: Install Homebridge
      role: homebridge
