---
- name: Upgrade packages
  hosts: all
  tasks:
  - name: Update package cache
    become: yes
    apt:
      update_cache: true
      cache_valid_time: 3600
  - name: Upgrade all packages to the latest version
    become: yes
    apt:
      upgrade: full
