- name: Install Node.js
  become: yes
  block:
  - name: Add nodesource key
    ansible.builtin.apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      id: 1655A0AB68576280

  - name: Add NodeSource repository
    ansible.builtin.apt_repository:
      repo: 'deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main'
      filename: /etc/apt/sources.list.d/nodesource

  - name: Install package
    apt:
      name: nodejs
      state: latest
