- name: Install Homebridge and required packages
  become: yes
  block:
  - name: Install required packages
    apt:
      pkg:
        - gcc
        - g++
        - make
        - python
        - net-tools

  - name: Install "homebridge" package globally
    community.general.npm:
      name: homebridge
      state: latest
      global: yes
      unsafe_perm: yes
    notify: Restart Homebridge

  - name: Install "homebridge-config-ui-x" package globally
    community.general.npm:
      name: homebridge-config-ui-x
      state: latest
      global: yes
      unsafe_perm: yes
    notify: Restart Homebridge

  - include_tasks: packages.yml

  - name: Populate service facts
    ansible.builtin.service_facts:

  - name: Setup Homebridge as a service
    ansible.builtin.command: hb-service install --user homebridge
    when: ansible_facts.services["homebridge.service"] is not defined
