- name: Install plugins
  community.general.npm:
    name: "{{ item }}"
    global: yes
    state: latest
  notify: Restart Homebridge
  loop:
    - homebridge-hue
    - homebridge-keylights
    - homebridge-plex-sensors
    - homebridge-rademacher-homepilot
    - homebridge-shell-switch
- name: Install plugins with unsafe_perms
  become: yes
  community.general.npm:
    name: "{{ item }}"
    global: yes
    state: latest
    unsafe_perm: yes
  notify: Restart Homebridge
  loop:
    - homebridge-philips-air
