- name: Set device name
  become: yes
  community.general.ini_file:
    path: /etc/raspotify/conf
    section:
    option: LIBRESPOT_NAME
    value: '{{ device_name }}'
    no_extra_spaces: yes
  notify: Restart raspotify

- name: Set bitrate
  become: yes
  community.general.ini_file:
    path: /etc/raspotify/conf
    section:
    option: LIBRESPOT_BITRATE
    value: '{{ bitrate }}'
    no_extra_spaces: yes
  notify: Restart raspotify

- name: Set device type
  become: yes
  community.general.ini_file:
    path: /etc/raspotify/conf
    section:
    option: LIBRESPOT_DEVICE_TYPE
    value: '{{ device_type }}'
    no_extra_spaces: yes
  notify: Restart raspotify
