galaxy_info:
  author: Lukas Spieß
  description: Set up Homebridge on a Raspberry Pi

  license: MIT

  min_ansible_version: 2.1

  platforms:
    - name: Debian
      versions:
      - buster

  galaxy_tags: []

dependencies:
  - role: nodejs
