name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    name: Run ansible-lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: ansible-lint
        uses: ansible/ansible-lint@main
